from typing import Union
import subprocess
import logging
import shutil
from pathlib import Path

log = logging.getLogger('falconry')


def run_command_local(command: str) -> bool:
    """Runs a command locally, returns True on success, False on failure.

    Arguments:
        command (str): command to run
    Returns:
        bool: True on success, False on failure
    """
    log.debug(f'Running command: {command}')
    result = subprocess.run(command.split(), stdout=subprocess.PIPE)
    return result.returncode == 0


def prepend(old: Union[str, list[str]], new: list[str]) -> list[str]:
    """For backward compatibility, prepend a list to another list
    or create new list from a single element and prepend it

    Arguments:
        old (Union[str, list[str]]): list to prepend
        new (list[str]): list to be prepended

    Returns:
        list[str]: prepended list
    """
    if isinstance(old, list):
        return old + new
    else:
        return [old] + new


def clean_dir(dir_path: str, keep_files: set[str]) -> None:
    """
    Remove everything inside `dir_path` except the files listed in `keep_files`.

    Arguments:
        dir_path (str): path to the directory to clean
        keep_files (set): set of file names to keep
    """
    base = Path(dir_path)

    log.debug(f"Cleaning {dir_path}. Keeping {keep_files}")
    keep_files_resolved = [Path(f).resolve() for f in keep_files]
    for entry in base.iterdir():
        log.debug(f'Processing {entry.name}')
        if entry.resolve() in keep_files_resolved:
            log.debug(f'Keeping {entry.name}')
            continue
        if entry.is_dir():
            shutil.rmtree(entry)
        else:
            entry.unlink()


def tail_file(filename: str, lines: int = 10, encoding: str = 'utf-8') -> str:
    """Returns last lines of a file

    Generated by Lumo Ai

    Arguments:
        filename (str): path to the file
        lines (int, optional): number of lines to return. Defaults to 10.
        encoding (str, optional): encoding of the file. Defaults to 'utf-8'.

    Returns:
        str: last lines of the file
    """
    with open(filename, 'rb') as f:
        f.seek(0, 2)  # Go to end
        file_size = f.tell()

        buffer_size = 8192
        blocks: list[bytes] = []
        bytes_read = 0

        while bytes_read < file_size and len(blocks) < lines:
            block_size = min(buffer_size, file_size - bytes_read)
            f.seek(file_size - bytes_read - block_size)
            blocks.append(f.read(block_size))
            bytes_read += block_size

        content = b''.join(reversed(blocks)).decode(encoding)
        return content
