import pytest
import tempfile
import os
from pathlib import Path
from unittest.mock import patch, MagicMock
from falconry.utils import run_command_local, prepend, clean_dir, tail_file


"""Based on code generated by Lumo AI"""


class TestRunCommandLocal:
    def test_success(self):
        with patch('subprocess.run') as mock_run:
            mock_run.return_value = MagicMock(returncode=0)
            assert run_command_local("echo hello") is True
            mock_run.assert_called_once()

    def test_failure(self):
        with patch('subprocess.run') as mock_run:
            mock_run.return_value = MagicMock(returncode=1)
            assert run_command_local("false") is False

    def test_command_splitting(self):
        with patch('subprocess.run') as mock_run:
            mock_run.return_value = MagicMock(returncode=0)
            run_command_local("ls -la /tmp")
            call_args = mock_run.call_args[0][0]
            assert call_args == ['ls', '-la', '/tmp']


class TestPrepend:
    def test_list_prepend(self):
        old = ['a', 'b']
        new = ['x', 'y']
        result = prepend(old, new)
        assert result == ['a', 'b', 'x', 'y']

    def test_string_prepend(self):
        old = 'single'
        new = ['x', 'y']
        result = prepend(old, new)
        assert result == ['single', 'x', 'y']

    def test_empty_new_list(self):
        old = ['a', 'b']
        new = []
        result = prepend(old, new)
        assert result == ['a', 'b']


class TestCleanDir:
    @pytest.fixture
    def temp_dir(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            # Create test files
            Path(tmpdir, 'keep1.txt').touch()
            Path(tmpdir, 'keep2.txt').touch()
            Path(tmpdir, 'delete.txt').touch()
            Path(tmpdir, 'subdir').mkdir()
            Path(tmpdir, 'subdir', 'file.txt').touch()
            yield tmpdir

    def test_keeps_specified_files(self, temp_dir):
        keep_files = {'keep1.txt', 'keep2.txt'}
        clean_dir(temp_dir, keep_files)

        assert Path(temp_dir, 'keep1.txt').exists()
        assert Path(temp_dir, 'keep2.txt').exists()
        assert not Path(temp_dir, 'delete.txt').exists()

    def test_removes_directories(self, temp_dir):
        keep_files = {'keep1.txt'}
        clean_dir(temp_dir, keep_files)

        assert not Path(temp_dir, 'subdir').exists()

    def test_empty_keep_set(self, temp_dir):
        clean_dir(temp_dir, set())

        assert not Path(temp_dir, 'keep1.txt').exists()
        assert not Path(temp_dir, 'keep2.txt').exists()
        assert not Path(temp_dir, 'delete.txt').exists()


class TestTailFile:
    @pytest.fixture
    def temp_file(self):
        with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.txt') as f:
            f.write('\n'.join([f'line{i}' for i in range(100)]))
        yield f.name
        os.unlink(f.name)

    def test_default_lines(self, temp_file):
        result = tail_file(temp_file)
        lines = result.strip().split('\n')
        assert len(lines) == 10
        for i in range(90, 100):
            assert f'line{i}' in lines

    def test_specific_lines(self, temp_file):
        result = tail_file(temp_file, lines=5)
        lines = result.strip().split('\n')
        assert len(lines) == 5
        for i in range(95, 100):
            assert f'line{i}' in lines

    def test_empty_file(self):
        with tempfile.NamedTemporaryFile(mode='w', delete=False) as f:
            fname = f.name
        try:
            result = tail_file(fname)
            assert result == ''
        finally:
            os.unlink(fname)

    def test_fewer_lines_than_requested(self):
        with tempfile.NamedTemporaryFile(mode='w', delete=False) as f:
            f.write('line1\nline2')
            fname = f.name
        try:
            result = tail_file(fname, lines=10)
            assert 'line1' in result
            assert 'line2' in result
        finally:
            os.unlink(fname)
