import pytest
import os
from falconry.mychdir import chdir
import tempfile

"""Based on code generated by Lumo AI"""


class TestChdir:
    @pytest.fixture
    def temp_dirs(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            yield os.getcwd(), tmpdir

    def test_changes_directory(self, temp_dirs):
        original, target = temp_dirs
        with chdir(target):
            assert os.getcwd() == target
        assert os.getcwd() == original

    def test_nested_contexts(self, temp_dirs):
        original, target = temp_dirs
        with tempfile.TemporaryDirectory() as tmpdir2:
            with chdir(target):
                assert os.getcwd() == target
                with chdir(tmpdir2):
                    assert os.getcwd() == tmpdir2
                assert os.getcwd() == target
            assert os.getcwd() == original

    def test_exception_in_context(self, temp_dirs):
        original, target = temp_dirs
        try:
            with chdir(target):
                raise ValueError("Test error")
        except ValueError:
            pass
        assert os.getcwd() == original
