import pytest
import tempfile
from pathlib import Path

from falconry.lock import LockFile, LockFileException, lock


"""Based on code generated by Lumo AI"""


class TestLockFile:
    @pytest.fixture
    def temp_lock_path(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            yield Path(tmpdir, 'test.lock')

    def test_create_lock(self, temp_lock_path):
        lock_file = LockFile(str(temp_lock_path))
        with lock_file:
            assert temp_lock_path.exists()
        assert not temp_lock_path.exists()

    def test_raises_if_exists(self, temp_lock_path):
        temp_lock_path.touch()
        with pytest.raises(LockFileException):
            LockFile(str(temp_lock_path))

    def test_context_manager_cleanup(self, temp_lock_path):
        with LockFile(str(temp_lock_path)):
            assert temp_lock_path.exists()
        assert not temp_lock_path.exists()

    def test_exception_during_context(self, temp_lock_path):
        try:
            with LockFile(str(temp_lock_path)):
                assert temp_lock_path.exists()
                raise ValueError("Test error")
        except ValueError:
            pass
        # Lock should still be cleaned up
        assert not temp_lock_path.exists()


class TestLockDecorator:
    @pytest.fixture
    def temp_lock_path(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            yield Path(tmpdir, 'test.lock')

    def test_decorator_applies_lock(self, temp_lock_path):
        class TestClass:
            def __init__(self):
                self.lockFile = str(temp_lock_path)

            def _check_lock(self):
                pass

            @lock
            def locked_method(self):
                assert temp_lock_path.exists()
                return "success"

        obj = TestClass()
        result = obj.locked_method()
        assert result == "success"
        assert not temp_lock_path.exists()

    def test_decorator_with_exception(self, temp_lock_path):
        class TestClass:
            def __init__(self):
                self.lockFile = str(temp_lock_path)

            def _check_lock(self):
                pass

            @lock
            def failing_method(self):
                assert temp_lock_path.exists()
                raise RuntimeError("Intentional failure")

        obj = TestClass()
        with pytest.raises(RuntimeError):
            obj.failing_method()
        # Lock should still be cleaned up
        assert not temp_lock_path.exists()
