from unittest.mock import patch, MagicMock
from falconry.cli import InputState, input_checker

"""Based on code generated by Lumo AI"""


class TestInputState:
    def test_enum_values(self):
        assert InputState.UNKNOWN.value == -1
        assert InputState.SUCCESS.value == 0
        assert InputState.TIMEOUT.value == 1


class TestInputChecker:
    def test_valid_input(self):
        valid_options = {'y': 'yes', 'n': 'no'}
        with patch('select.select') as mock_select:
            mock_select.return_value = ([MagicMock()], [], [])
            with patch('sys.stdin.readline') as mock_read:
                mock_read.return_value = 'y\n'
                state, inp = input_checker(valid_options, timeout=1)
                assert state == InputState.SUCCESS
                assert inp == 'y'

    def test_invalid_input(self):
        valid_options = {'y': 'yes', 'n': 'no'}
        with patch('select.select') as mock_select:
            mock_select.return_value = ([MagicMock()], [], [])
            with patch('sys.stdin.readline') as mock_read:
                mock_read.return_value = 'invalid\n'
                state, inp = input_checker(valid_options, timeout=1)
                assert state == InputState.UNKNOWN
                assert inp == 'invalid'

    def test_timeout(self):
        valid_options = {'y': 'yes', 'n': 'no'}
        with patch('select.select') as mock_select:
            mock_select.return_value = ([], [], [])
            state, inp = input_checker(valid_options, timeout=1)
            assert state == InputState.TIMEOUT
            assert inp is None

    def test_silent_mode_no_output(self):
        valid_options = {'y': 'yes'}
        with patch('select.select') as mock_select:
            mock_select.return_value = ([MagicMock()], [], [])
            with patch('sys.stdin.readline') as mock_read:
                mock_read.return_value = 'y\n'
                with patch('logging.Logger.info') as mock_log:
                    state, inp = input_checker(valid_options, silent=True)
                    mock_log.assert_not_called()
                    assert state == InputState.SUCCESS
                    assert inp == 'y'

    def test_message_printed(self):
        valid_options = {'y': 'yes'}
        with patch('select.select') as mock_select:
            mock_select.return_value = ([], [], [])
            with patch('logging.Logger.info') as mock_log:
                input_checker(valid_options, message="Custom message", timeout=1)
                mock_log.assert_any_call("Custom message")
